# ==============================================================================
# R/config_packages.R
# Uygulama genelinde kullanılan tüm paketlerin yüklenmesi.
# global.R tarafından en başta source() ile çağrılır.
# ==============================================================================

library(arrow)
library(base64enc)
library(cellranger)
library(cli)
library(commonmark)
library(curl)
library(data.table)
library(DBI)
library(dplyr)
library(DT)
library(duckdb)
library(fastmatch)
library(future)
library(glue)
library(htmltools)
library(httr)
library(jsonlite)
library(later)
library(lubridate)
library(markdown)
library(odbc)
library(openssl)
library(pdftools)
library(pool)
library(promises)
library(purrr)
library(readr)
library(readxl)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(stringdist)
library(stringi)
library(stringr)
library(tibble)
library(tidyr)
library(urltools)
library(writexl)
library(xml2)
library(av)