# R/module_app_loading.R
# Dosya Yolu: R/module_app_loading.R
# Açıklama: Uygulama açılışında gösterilen modern, çok aşamalı yükleme ekranı.
#   SSO kimlik doğrulama, oturum kurulumu ve çalışma alanı hazırlığı boyunca tüm
#   ekranı kaplar ve gerçek ilerlemeyi aşama aşama yansıtır. Giriş animasyonu
#   kapalıyken derin uzay statik içeriğinin parlamasını engeller ve doğrudan
#   karşılama ekranına geçişi yönetir. Tüm stil/script satır içidir; bu sayede
#   harici varlık yüklenmesini beklemeden ilk boyamada görünür olur.

#' Yükleme Ekranı CSS Stilleri
#' @description Açılış katmanının satır içi CSS metnini döndürür.
#' @return Karakter dizisi (CSS)
app_loading_styles <- function() {
  paste(
    "#app-loading-overlay{",
    "  display:flex;align-items:center;justify-content:center;",
    "  font-family:'Segoe UI','Inter',system-ui,-apple-system,sans-serif;",
    "  opacity:1;transition:opacity .6s ease,visibility .6s ease;}",
    "#app-loading-overlay.app-loading-hidden{",
    "  opacity:0;visibility:hidden;pointer-events:none;}",
    "html.mergen-skip-intro #deep-space-container{display:none !important;}",
    "#app-loading-overlay .app-loading-stars{",
    "  position:absolute;inset:0;pointer-events:none;opacity:.55;",
    "  background-image:",
    "    radial-gradient(1.4px 1.4px at 16% 22%,#cdd6ff,transparent),",
    "    radial-gradient(1.2px 1.2px at 78% 16%,#aab6ff,transparent),",
    "    radial-gradient(1.6px 1.6px at 64% 70%,#ffffff,transparent),",
    "    radial-gradient(1.1px 1.1px at 28% 82%,#9fb0ff,transparent),",
    "    radial-gradient(1.3px 1.3px at 88% 56%,#dfe6ff,transparent),",
    "    radial-gradient(1px 1px at 42% 40%,#c2ccff,transparent);",
    "  animation:appLoadingTwinkle 4.6s ease-in-out infinite;}",
    "#app-loading-overlay .app-loading-aurora{",
    "  position:absolute;left:50%;top:36%;width:560px;height:560px;",
    "  transform:translate(-50%,-50%);pointer-events:none;",
    "  background:radial-gradient(circle,rgba(124,77,255,0.22),transparent 62%);",
    "  filter:blur(26px);animation:appLoadingBreathe 5.4s ease-in-out infinite;}",
    "#app-loading-overlay .app-loading-stage{",
    "  position:relative;display:flex;flex-direction:column;align-items:center;",
    "  text-align:center;padding:0 28px;}",
    "#app-loading-overlay .app-loading-emblem{",
    "  position:relative;width:132px;height:132px;margin-bottom:30px;}",
    "#app-loading-overlay .app-loading-ring{",
    "  position:absolute;inset:0;border-radius:50%;}",
    "#app-loading-overlay .app-loading-ring-outer{",
    "  border:2px solid rgba(129,140,248,0.16);",
    "  border-top-color:#818cf8;border-right-color:rgba(129,140,248,0.55);",
    "  animation:appLoadingSpin 2.6s linear infinite;}",
    "#app-loading-overlay .app-loading-ring-mid{",
    "  inset:20px;border:2px solid rgba(52,211,153,0.12);",
    "  border-bottom-color:#34d399;border-left-color:rgba(52,211,153,0.5);",
    "  animation:appLoadingSpinRev 3.4s linear infinite;}",
    "#app-loading-overlay .app-loading-orbit{",
    "  position:absolute;inset:0;animation:appLoadingSpin 5.5s linear infinite;}",
    "#app-loading-overlay .app-loading-dot{",
    "  position:absolute;width:9px;height:9px;border-radius:50%;",
    "  margin:-4.5px 0 0 -4.5px;",
    "  box-shadow:0 0 12px 2px currentColor;}",
    "#app-loading-overlay .app-loading-dot-1{",
    "  top:0;left:50%;color:#818cf8;background:#a5b0ff;}",
    "#app-loading-overlay .app-loading-dot-2{",
    "  top:50%;left:100%;color:#34d399;background:#6ee7b7;}",
    "#app-loading-overlay .app-loading-dot-3{",
    "  top:100%;left:50%;color:#7c4dff;background:#b69bff;}",
    "#app-loading-overlay .app-loading-core{",
    "  position:absolute;inset:38px;border-radius:50%;",
    "  background:radial-gradient(circle at 38% 32%,#c6b8ff,#7c4dff 62%,#3a2a8c);",
    "  box-shadow:0 0 26px 6px rgba(124,77,255,0.55),",
    "    inset 0 0 14px rgba(255,255,255,0.35);",
    "  animation:appLoadingPulse 2.1s ease-in-out infinite;}",
    "#app-loading-overlay .app-loading-wordmark{",
    "  font-size:30px;font-weight:700;letter-spacing:.16em;",
    "  color:#eef1fb;text-transform:uppercase;}",
    "#app-loading-overlay .app-loading-wordmark-accent{",
    "  margin-left:.32em;",
    "  background:linear-gradient(120deg,#818cf8,#34d399);",
    "  -webkit-background-clip:text;background-clip:text;",
    "  -webkit-text-fill-color:transparent;}",
    "#app-loading-overlay .app-loading-tagline{",
    "  margin-top:8px;font-size:12px;letter-spacing:.34em;",
    "  text-transform:uppercase;color:#6b76a0;}",
    "#app-loading-overlay .app-loading-status{",
    "  display:flex;align-items:center;gap:10px;margin-top:34px;",
    "  min-height:20px;}",
    "#app-loading-overlay .app-loading-status-pulse{",
    "  width:8px;height:8px;border-radius:50%;background:#34d399;",
    "  box-shadow:0 0 10px 2px rgba(52,211,153,0.7);",
    "  animation:appLoadingBlink 1.25s ease-in-out infinite;}",
    "#app-loading-overlay .app-loading-status-text{",
    "  font-size:14.5px;color:#aab2d4;letter-spacing:.02em;}",
    "#app-loading-overlay .app-loading-progress{",
    "  position:relative;width:248px;height:3px;margin-top:20px;",
    "  border-radius:3px;overflow:hidden;",
    "  background:rgba(255,255,255,0.08);}",
    "#app-loading-overlay .app-loading-progress-fill{",
    "  position:absolute;left:0;top:0;height:100%;width:8%;border-radius:3px;",
    "  background:linear-gradient(90deg,#7c4dff,#818cf8 55%,#34d399);",
    "  box-shadow:0 0 12px rgba(129,140,248,0.7);",
    "  transition:width .7s cubic-bezier(.4,0,.2,1);}",
    "#app-loading-overlay .app-loading-progress-fill::after{",
    "  content:'';position:absolute;inset:0;",
    "  background:linear-gradient(90deg,transparent,",
    "    rgba(255,255,255,0.55),transparent);",
    "  animation:appLoadingShimmer 1.5s linear infinite;}",
    "@keyframes appLoadingSpin{to{transform:rotate(360deg);}}",
    "@keyframes appLoadingSpinRev{to{transform:rotate(-360deg);}}",
    "@keyframes appLoadingPulse{",
    "  0%,100%{transform:scale(1);opacity:.92;}",
    "  50%{transform:scale(1.08);opacity:1;}}",
    "@keyframes appLoadingBlink{",
    "  0%,100%{opacity:.35;}50%{opacity:1;}}",
    "@keyframes appLoadingShimmer{0%{transform:translateX(-100%);}",
    "  100%{transform:translateX(100%);}}",
    "@keyframes appLoadingTwinkle{",
    "  0%,100%{opacity:.4;}50%{opacity:.75;}}",
    "@keyframes appLoadingBreathe{",
    "  0%,100%{opacity:.5;transform:translate(-50%,-50%) scale(.92);}",
    "  50%{opacity:.85;transform:translate(-50%,-50%) scale(1.06);}}",
    "@media (prefers-reduced-motion:reduce){",
    "  #app-loading-overlay .app-loading-ring,",
    "  #app-loading-overlay .app-loading-orbit,",
    "  #app-loading-overlay .app-loading-core,",
    "  #app-loading-overlay .app-loading-aurora,",
    "  #app-loading-overlay .app-loading-stars,",
    "  #app-loading-overlay .app-loading-status-pulse,",
    "  #app-loading-overlay .app-loading-progress-fill::after{",
    "    animation:none !important;}}",
    sep = "\n"
  )
}

#' Yükleme Ekranı İstemci Betiği
#' @description Açılış katmanını yöneten satır içi JavaScript metnini döndürür.
#' @return Karakter dizisi (JavaScript)
app_loading_script <- function() {
  paste(
    "(function(){",
    "  'use strict';",
    "  var overlay=document.getElementById('app-loading-overlay');",
    "  if(!overlay) return;",
    "  var STAGES=[",
    "    {key:'boot',label:'Sistem çalıştırılıyor',pct:14},",
    "    {key:'connect',label:'Sunucuya bağlanılıyor',pct:32},",
    "    {key:'auth',label:'Kimlik doğrulanıyor',pct:50},",
    "    {key:'session',label:'Oturumunuz hazırlanıyor',pct:68},",
    "    {key:'workspace',label:'Çalışma alanı hazırlanıyor',pct:86},",
    "    {key:'ready',label:'Neredeyse hazır',pct:97}];",
    "  var stageIndex=-1,finished=false,shinyReady=false;",
    "  var ssoActive=false,ssoResolved=false,skipIntro=false,appReadyAt=0;",
    "  try{var raw=localStorage.getItem('mergen_settings');",
    "    if(raw){var s=JSON.parse(raw);skipIntro=!!(s&&s.skip_intro===true);}",
    "  }catch(e){}",
    "  if(skipIntro){document.documentElement.classList.add('mergen-skip-intro');}",
    "  var statusText=overlay.querySelector('.app-loading-status-text');",
    "  var progressFill=overlay.querySelector('.app-loading-progress-fill');",
    "  function setStage(key){",
    "    var idx=-1;",
    "    for(var i=0;i<STAGES.length;i++){if(STAGES[i].key===key){idx=i;break;}}",
    "    if(idx<0||idx<=stageIndex||finished) return;",
    "    stageIndex=idx;",
    "    if(statusText) statusText.textContent=STAGES[idx].label;",
    "    if(progressFill) progressFill.style.width=STAGES[idx].pct+'%';",
    "  }",
    "  function finish(){",
    "    if(finished) return;",
    "    finished=true;",
    "    if(progressFill) progressFill.style.width='100%';",
    "    overlay.classList.add('app-loading-hidden');",
    "    window.setTimeout(function(){",
    "      if(overlay) overlay.style.display='none';",
    "    },700);",
    "  }",
    "  function welcomeVisible(){",
    "    var root=document.querySelector('.modern-welcome-root');",
    "    return !!(root&&root.offsetParent!==null);",
    "  }",
    "  function evaluate(){",
    "    if(finished) return;",
    "    if(!shinyReady||!ssoResolved) return;",
    "    setStage('workspace');",
    "    if(skipIntro){",
    "      if(welcomeVisible()){setStage('ready');window.setTimeout(finish,600);return;}",
    "      var body=document.body;",
    "      if(body&&body.classList.contains('app-ready')){",
    "        if(!appReadyAt){appReadyAt=Date.now();}",
    "        else if(Date.now()-appReadyAt>2600){",
    "          setStage('ready');window.setTimeout(finish,300);}",
    "      }",
    "    }else{",
    "      setStage('ready');window.setTimeout(finish,550);",
    "    }",
    "  }",
    "  function startSsoWatch(){",
    "    var ssoTimer=window.setInterval(function(){",
    "      if(finished){window.clearInterval(ssoTimer);return;}",
    "      var ssoErr=document.getElementById('sso_module-sso_error');",
    "      if(ssoErr&&window.getComputedStyle(ssoErr).display!=='none'){",
    "        window.clearInterval(ssoTimer);finish();return;}",
    "      var ssoOv=document.getElementById('sso_module-sso_overlay');",
    "      if(ssoOv&&ssoOv.classList.contains('sso-auth-hidden')){",
    "        window.clearInterval(ssoTimer);ssoResolved=true;",
    "        setStage('session');evaluate();}",
    "    },150);",
    "  }",
    "  function detectSso(){",
    "    try{var cfgEl=document.getElementById('sso_module-sso_config_data');",
    "      if(cfgEl){var c=JSON.parse(cfgEl.textContent||'{}');",
    "        ssoActive=!!(c&&c.enabled);}",
    "    }catch(e){}",
    "    if(ssoActive){setStage('auth');startSsoWatch();}",
    "    else{ssoResolved=true;}",
    "    evaluate();",
    "  }",
    "  setStage('boot');",
    "  if(document.readyState==='loading'){",
    "    document.addEventListener('DOMContentLoaded',detectSso);",
    "  }else{detectSso();}",
    "  document.addEventListener('shiny:connected',function(){",
    "    setStage(ssoActive?'auth':'connect');",
    "  });",
    "  document.addEventListener('shiny:sessioninitialized',function(){",
    "    shinyReady=true;",
    "    if(!ssoActive) setStage('session');",
    "    evaluate();",
    "  });",
    "  document.addEventListener('shiny:disconnected',function(){finish();});",
    "  var pollTimer=window.setInterval(function(){",
    "    if(finished){window.clearInterval(pollTimer);return;}",
    "    evaluate();",
    "  },140);",
    "  window.setTimeout(function(){finish();},22000);",
    "  window.MergenAppLoading={finish:finish,setStage:setStage};",
    "})();",
    sep = "\n"
  )
}

#' Uygulama Yükleme Ekranı UI
#' @description Açılış yükleme katmanını ve satır içi stil/script bloklarını üretir.
#'   ui.R içinde, mümkün olan en erken noktada çağrılmalıdır.
#' @return Shiny tagList
appLoadingUI <- function() {
  tagList(
    tags$div(
      id = "app-loading-overlay",
      # Kritik konum/zemin satır içinde: <style> ayrıştırılmadan da ekranı
      # opak biçimde kaplar. Zemin gradyanı da satır içi tutulur; aksi halde
      # satır içi düz renk, stil bloğundaki gradyanı özgüllükle ezerdi.
      style = paste0(
        "position:fixed;top:0;left:0;right:0;bottom:0;z-index:2147483600;",
        "background:",
        "radial-gradient(circle at 50% 34%,rgba(124,77,255,0.20),transparent 56%),",
        "radial-gradient(circle at 50% 104%,rgba(47,109,246,0.16),transparent 60%),",
        "linear-gradient(165deg,#070b1e 0%,#0c1233 50%,#070a18 100%);"
      ),
      tags$div(class = "app-loading-stars"),
      tags$div(class = "app-loading-aurora"),
      tags$div(
        class = "app-loading-stage",
        tags$div(
          class = "app-loading-emblem",
          tags$div(class = "app-loading-ring app-loading-ring-outer"),
          tags$div(class = "app-loading-ring app-loading-ring-mid"),
          tags$div(
            class = "app-loading-orbit",
            tags$span(class = "app-loading-dot app-loading-dot-1"),
            tags$span(class = "app-loading-dot app-loading-dot-2"),
            tags$span(class = "app-loading-dot app-loading-dot-3")
          ),
          tags$div(class = "app-loading-core")
        ),
        tags$div(
          class = "app-loading-wordmark",
          tags$span("MERGEN", class = "app-loading-wordmark-primary"),
          tags$span("Bilge", class = "app-loading-wordmark-accent")
        ),
        tags$div(class = "app-loading-tagline", "Yapay Zeka Asistanı"),
        tags$div(
          class = "app-loading-status",
          tags$span(class = "app-loading-status-pulse"),
          tags$span(class = "app-loading-status-text", "Sistem çalıştırılıyor")
        ),
        tags$div(
          class = "app-loading-progress",
          tags$div(class = "app-loading-progress-fill")
        )
      ),
      tags$style(HTML(app_loading_styles())),
      tags$script(HTML(app_loading_script()))
    )
  )
}
